@extends('layouts.app', ['title' => 'Sumbangan'])

@section('content')
@php($labels = ['pending' => 'Menunggu semakan bendahari', 'treasurer_verified' => 'Menunggu kelulusan admin', 'approved' => 'Diluluskan', 'rejected' => 'Ditolak'])
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
    <div><p class="dashboard-kicker mb-1">Kewangan kelab</p><h1 class="h3 mb-0">Sumbangan</h1><p class="text-muted mb-0">Mohon bantuan sumbangan dan semak status kelulusan.</p></div>
    <a class="btn btn-danger" href="{{ route('donations.create') }}"><i class="bi bi-heart me-2" aria-hidden="true"></i>Mohon Sumbangan</a>
</div>
<div class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end"><div class="col-md-5"><label class="form-label" for="donation-category">Jenis Sumbangan</label><select class="form-select" id="donation-category" name="category"><option value="">Semua jenis</option>@foreach($types as $type)<option value="{{ $type }}" @selected(request('category') === $type)>{{ $type }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label" for="donation-status">Status</label><select class="form-select" id="donation-status" name="status"><option value="">Semua status</option>@foreach($labels as $key => $label)<option value="{{ $key }}" @selected(request('status') === $key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-outline-danger w-100">Tapis</button></div></form></div></div>
<div class="card"><div class="table-responsive"><table class="table mobile-records align-middle mb-0"><thead><tr><th>Jenis Sumbangan</th><th>Ahli</th><th>Had Bendahari</th><th>Amaun Diluluskan</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($donations as $donation)<tr><td data-label="Jenis"><strong>{{ $donation->category }}</strong><div class="small text-muted">{{ $donation->request_date->format('d/m/Y') }}</div></td><td data-label="Ahli">{{ $donation->user->name }}</td><td data-label="Had">{{ $donation->limit_amount !== null ? 'RM '.number_format((float) $donation->limit_amount, 2) : '-' }}</td><td data-label="Amaun">{{ $donation->amount !== null ? 'RM '.number_format((float) $donation->amount, 2) : '-' }}</td><td data-label="Status"><span class="badge bg-secondary">{{ $labels[$donation->status] ?? $donation->status }}</span></td><td><a class="btn btn-sm btn-outline-danger" href="{{ route('donations.show', $donation) }}">Semak</a></td></tr>@empty<tr><td colspan="6"><div class="dashboard-empty-state my-3"><span class="stat-icon"><i class="bi bi-heart" aria-hidden="true"></i></span><p class="text-muted mb-0">Tiada permohonan sumbangan.</p></div></td></tr>@endforelse
</tbody></table></div></div><div class="mt-3">{{ $donations->links() }}</div>
@endsection
