@extends('layouts.app', ['title' => 'Semakan Sumbangan'])

@section('content')
<div class="row g-4"><div class="col-lg-7"><div class="card"><div class="card-body"><h1 class="h4 mb-1">{{ $donation->category }}</h1><span class="badge {{ \App\Support\PolistaffLabels::statusClass($donation->status) }}">{{ \App\Support\PolistaffLabels::status($donation->status) }}</span><hr><dl class="row"><dt class="col-sm-5">Pemohon</dt><dd class="col-sm-7">{{ $donation->user->name }}</dd><dt class="col-sm-5">Keterangan</dt><dd class="col-sm-7">{{ $donation->description ?: '-' }}</dd><dt class="col-sm-5">Had Bendahari</dt><dd class="col-sm-7">{{ $donation->limit_amount !== null ? 'RM '.number_format((float) $donation->limit_amount, 2) : '-' }}</dd><dt class="col-sm-5">Amaun Sumbangan</dt><dd class="col-sm-7">{{ $donation->amount !== null ? 'RM '.number_format((float) $donation->amount, 2) : 'Belum ditentukan' }}</dd><dt class="col-sm-5">Catatan Bendahari</dt><dd class="col-sm-7">{{ $donation->treasurer_notes ?: '-' }}</dd><dt class="col-sm-5">Transaksi</dt><dd class="col-sm-7">@if($donation->transaction)<a href="{{ route('transactions.show', $donation->transaction) }}">{{ $donation->transaction->receipt_number }}</a>@else - @endif</dd></dl></div></div></div><div class="col-lg-5"><div class="card"><div class="card-body"><h2 class="h5 soft-panel-title">Kelulusan</h2>
@if(auth()->user()->hasRole('treasurer','admin') && $donation->status === 'pending')<form method="post" action="{{ route('donations.verify', $donation) }}" data-confirm="Tetapkan had dan hantar sumbangan kepada pengerusi?"><p class="small text-muted">Tetapkan had maksimum berdasarkan bajet kelab.</p>@csrf @method('patch')<label class="form-label" for="limit_amount">Had Sumbangan</label><input class="form-control mb-2" id="limit_amount" type="number" name="limit_amount" min="0.01" step="0.01" required><label class="form-label" for="treasurer_notes">Catatan</label><textarea class="form-control mb-2" id="treasurer_notes" name="treasurer_notes" rows="3"></textarea><button class="btn btn-danger w-100">Sokong &amp; Hantar kepada Pengerusi</button></form>@endif
@if(auth()->user()->hasRole('admin') && $donation->status === 'treasurer_verified')<form method="post" action="{{ route('donations.approve', $donation) }}" data-confirm="Luluskan sumbangan ini dan tolak amaun daripada baki kelab?"><p class="small text-muted">Had bendahari: <strong>RM {{ number_format((float) $donation->limit_amount, 2) }}</strong></p>@csrf @method('patch')<label class="form-label" for="amount">Amaun Sumbangan</label><input class="form-control mb-2" id="amount" type="number" name="amount" min="0.01" max="{{ $donation->limit_amount }}" step="0.01" required><label class="form-label" for="review_notes">Catatan</label><textarea class="form-control mb-2" id="review_notes" name="review_notes" rows="3"></textarea><button class="btn btn-danger w-100">Luluskan Sumbangan</button></form>@endif
@if(auth()->user()->hasRole('admin') && in_array($donation->status, ['pending','treasurer_verified'], true))<form method="post" action="{{ route('donations.reject', $donation) }}" class="mt-3" data-confirm="Tolak permohonan sumbangan ini?"><div class="mb-2"><label class="form-label" for="reject_notes">Sebab Ditolak</label><textarea class="form-control" id="reject_notes" name="review_notes" rows="3" required></textarea></div>@csrf @method('patch')<button class="btn btn-outline-secondary w-100">Tolak Sumbangan</button></form>@endif
@if(in_array($donation->status, ['approved','rejected'], true))<p class="text-muted mb-0">Tiada tindakan tersedia.</p>@endif
</div></div></div></div>
@endsection
